---
title: "Reproducible Research Project 1 (Activity Monitoring Data)"
author: "Aeron Chester Dino"
date: "2023-03-19"
output: html_document
---


## Loading and preprocessing the data.

```{r, echo=TRUE}
      setwd("c:/Users/Aeron/Desktop/Data Science/ReproducibleResearchProject1")
      download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", destfile = "activity.zip")
      unzip("activity.zip", exdir = "c:/Users/Aeron/Desktop/Data Science/ReproducibleResearchProject1")
      activity <- read.csv("activity.csv", colClasses=c("numeric", "Date", "numeric"))
      dim(activity)
      str(activity)
      head(activity)


```
## What is mean total number of steps taken per day?
```{r, echo=TRUE}
      cleandata<-activity[!(is.na(activity$steps)), ]
      totalStepsDay <- aggregate(steps ~ date, cleandata, sum)
      
      hist(totalStepsDay$steps, breaks=20, xlab="Number of Steps Taken", 
           main="Histogram of the Total Number of Steps Taken per Day", family="serif")
      
      # Calculate the mean and median
      mean_steps_per_day <- mean(totalStepsDay$steps)
      median_steps_per_day <- median(totalStepsDay$steps)
      
      # Print the mean and median
      cat("Mean of total number of steps per day:", mean_steps_per_day, "\n")
      cat("Median of total number of steps per day:", median_steps_per_day, "\n")

```

## What is the average daily activity pattern?
```{r, echo=TRUE}

      avg_steps_per_interval <- aggregate(steps ~ interval, data = activity, mean, na.rm = TRUE)
      plot(avg_steps_per_interval$interval, avg_steps_per_interval$steps, type = "l", xlab = "5-minute interval", ylab = "Average number of steps")
      
      max_interval <- avg_steps_per_interval$interval[which.max(avg_steps_per_interval$steps)]
      
      cat("The interval with the maximum average number of steps is", max_interval)
```

## Imputing missing values

Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
``` {r, echo=TRUE}

      totalNA<-sum(rowSums(is.na(activity)) > 0)
      cat("The total number of missing values is", totalNA)
```
Devise a strategy for filling in all of the missing values in the dataset.

```{r, echo=TRUE}
# Imputing NA
library(dplyr)

imputed <- activity %>%
  group_by(interval) %>%
  mutate(steps_imputed = ifelse(is.na(steps), mean(steps, na.rm = TRUE), steps))
# Making histogram of Imputed Data
 totalStepsDayImputed <- aggregate(steps_imputed ~ date, imputed, sum)
      
      hist(totalStepsDayImputed$steps_imputed, breaks=20, xlab="Number of Steps Taken", 
           main="Histogram of the Total Number of Steps Taken per Day", family="serif")
      
 
# Calculate the mean and median
      impmean_steps_per_day <- mean(totalStepsDayImputed$steps_imputed)
      impmedian_steps_per_day <- median(totalStepsDayImputed$steps_imputed)
      
# Print the mean and median
      cat("Mean of total number of steps per day:", impmean_steps_per_day, "\n")
      cat("Median of total number of steps per day:", impmedian_steps_per_day, "\n")

```

# Comparison og Two Histogram

